
package java101;
	
public class Checker
{
	/* Static method that takes a Sudoku puzzle and returns a new puzzle with one number randomly changed */ 
	public static int[][] damage(int[][] puzzle)
	{
		int[][] newPuzzle = puzzle.clone();
		int row = (int) (Math.random() * puzzle.length);
		int col = (int) (Math.random() * puzzle[puzzle.length - 1].length);
		int change;
		do
		{
			change = (int) (Math.random() * puzzle.length);
		} while (change == newPuzzle[row][col]);
		newPuzzle[row][col] = change;
		return newPuzzle;
	}

	public static void main(String[] args)
	{
		/* Sample Sudoku puzzle with the correct solution */
		int[][] sample =   {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,6,8,5,3,7,9,1},
        					{7,1,3,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};
		
		Sudoku sudoku1 = new Sudoku(sample);
		//System.out.println(sudoku1.rowChecker());
		//System.out.println(sudoku1.columnChecker());
		//System.out.println(sudoku1.subSquareChecker());


		/* Sudoku puzzle with problems in the rows */
        int[][] sampleR =  {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,3,8,5,3,7,9,1},
        					{7,1,6,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};
        
        Sudoku sudoku2 = new Sudoku(sampleR);
      	//System.out.println(sudoku2.rowChecker());
      	//System.out.println(sudoku2.columnChecker());
      	//System.out.println(sudoku2.subSquareChecker());

       

		/* Sudoku puzzle with problems in the columns */
        int[][] sampleC =  {{5,3,4,6,7,8,9,1,2},
        					{6,7,2,1,9,5,3,4,8},
        					{1,9,8,3,4,2,5,6,7},
        					{8,5,9,7,6,1,4,2,3},
        					{4,2,6,5,8,3,7,9,1},
        					{7,1,3,9,2,4,8,5,6},
        					{9,6,1,5,3,7,2,8,4},
        					{2,8,7,4,1,9,6,3,5},
        					{3,4,5,2,8,6,1,7,9}};
        
        Sudoku sudoku3 = new Sudoku(sampleC);
        //System.out.println(sudoku3.rowChecker());
  		//System.out.println(sudoku3.columnChecker());
      	//System.out.println(sudoku3.subSquareChecker());

        
      
		/* Sudoku puzzle with problems in the subsquares */
        int[][] sampleS =  {{5,3,4,6,7,8,9,1,2},
							{6,7,2,1,9,5,3,4,8},
							{1,9,8,3,4,2,5,6,7},
							{8,5,7,9,6,4,1,2,3},
							{4,2,6,8,5,3,7,9,1},
							{9,4,3,7,2,1,8,5,6},
							{7,6,1,5,3,9,2,8,4},
							{2,8,9,4,1,7,6,3,5},
							{3,1,5,2,8,6,4,7,9}};
        
        Sudoku sudoku4 = new Sudoku(sampleS);
  		//System.out.println(sudoku4.rowChecker());
  		//System.out.println(sudoku4.columnChecker());
  		//System.out.println(sudoku4.subSquareChecker());


		/* Sudoku puzzle with the problem generated by the damage method */
        int[][] badSample = damage(sample);
	}
}


